[Mikhail_Ilichev] Tasks 11-20
miffn3/ui-internship-lwo2 pull request #2
Opened 2019-09-10 19:57 UTC by miffn3

2019-09-11 09:03 UTC, KalachevDev approved these changes

2019-09-11 09:03 UTC, KalachevDev commented on tasks/13_largest-of-four/largest-of-four.js
> +  for (let i = 0; i < arr.length; i++) {
Just a thought it could be done other way as well:
`
export function largestOfFour (arr) {
    return arr.map(subArray => subArray.reduce((accum, current)) => Math.max(accum, current)));
}
`

You don't need to change anything in your implementation just take a look at `.map` function

2019-09-11 09:03 UTC, KalachevDev commented on tasks/14_clone-arr/clone-arr.js
> +  return arr.slice();
again, just a thought you could use spread operator here, but _again_ you don't need to change your implementation :), JFYI

2019-09-11 09:03 UTC, KalachevDev commented on tasks/18_humanize-format/humanize-format.js
> +  if (num === undefined) {
What's about zero?

2019-09-11 09:18 UTC, KalachevDev submitted a review, later dismissed
Good job!

2019-09-11 13:03 UTC, miffn3 commented on tasks/13_largest-of-four/largest-of-four.js
> +  for (let i = 0; i < arr.length; i++) {
Got it, thanks)
I've tried it out in console

2019-09-11 13:04 UTC, miffn3 commented on tasks/14_clone-arr/clone-arr.js
> +  return arr.slice();
I've read about spread operator)

2019-09-11 13:06 UTC, miffn3 commented on tasks/18_humanize-format/humanize-format.js
> +  if (num === undefined) {
I think zero should be like "0th"

2019-09-12 06:36 UTC, alexkond requested changes

2019-09-12 06:36 UTC, alexkond commented on tasks/16_repeat-string/repeat-string.js
> +  for (let i = 1; i < num; i++) {
Look closely to `String` prototype. It has a method that is designed for such cases.

2019-09-12 06:36 UTC, alexkond commented on tasks/18_humanize-format/humanize-format.js
> +  if (lastDigit === 1) {
Consider using `switch` in such cases.

2019-09-12 06:36 UTC, alexkond commented on tasks/20_truncate-array/truncate-array.js
> +  return copyArr.slice(size, copyArr.length);
Why you are doing `slice()` twice?

2019-09-12 07:59 UTC, vovcyan submitted a review, later dismissed

2019-09-12 08:28 UTC, miffn3 commented on tasks/16_repeat-string/repeat-string.js
> +  for (let i = 1; i < num; i++) {
Changed my implementation to `repeat()` operator

2019-09-12 08:31 UTC, miffn3 commented on tasks/18_humanize-format/humanize-format.js
> +  if (lastDigit === 1) {
Changed it to `switch`

2019-09-12 08:33 UTC, miffn3 commented on tasks/20_truncate-array/truncate-array.js
> +  return copyArr.slice(size, copyArr.length);
My bad, fixed it

2019-09-12 08:43 UTC, KalachevDev approved these changes

2019-09-12 08:43 UTC, vovcyan approved these changes

2019-09-12 09:02 UTC, alexkond approved these changes

2019-09-12 09:03 UTC, merged