[Mikhail Ilichev] Tasks 71-80
miffn3/ui-internship-lwo2 pull request #8
Opened 2019-09-19 16:48 UTC by miffn3

2019-09-20 06:54 UTC, KalachevDev requested changes

2019-09-20 06:54 UTC, KalachevDev commented on tasks/71_binary-encode/binary-encode.js
> +export function binaryEncode(str) {
Again, let's not name arguments as `str, num, bool` etc

2019-09-20 06:54 UTC, KalachevDev commented on tasks/71_binary-encode/binary-encode.js
> +    result = 0 + result;
Seem this might be extracted to another function

2019-09-20 06:54 UTC, KalachevDev commented on tasks/71_binary-encode/binary-encode.js
> +      encodeChar = 0 + encodeChar;
the same as above

2019-09-20 06:54 UTC, KalachevDev commented on tasks/72_carrying/carrying.js
> +  if (typeof a !== 'number') {
Seem you need to work with arguments here

2019-09-20 06:54 UTC, KalachevDev commented on tasks/73_check-for-palindromes/check-for-palindromes.js
> +  for (let i = 0; i < n; i++) {
Can't we just reverse string and compare it with source?

2019-09-20 06:54 UTC, KalachevDev commented on tasks/74_dna-pairing/dna-pairing.js
> +    switch (dnas[i]) {
I'd suggest to create some dictionary instead of doing switch

2019-09-20 06:54 UTC, KalachevDev commented on tasks/75_complementary-dna/complementary-dna.js
> +      case ('C'):
Could you work on more elegant solution?

2019-09-20 06:54 UTC, KalachevDev commented on tasks/76_deep-object-clone/deep-object-clone.js
> +  const copied = (function copy(toCopy) {
toCopy name is not obvious. What's about `source`?

2019-09-20 06:54 UTC, KalachevDev commented on tasks/76_deep-object-clone/deep-object-clone.js
> +      if (typeof toCopy[key] === 'object' && obj[key] !== null) {
```
const testObject = {
    foo: function () {}
};

testObject.foo.a = { c: { a: 'Copy me too please! I really want to be copied' } };
```

2019-09-20 06:54 UTC, KalachevDev commented on tasks/76_deep-object-clone/deep-object-clone.js
> +      if (typeof toCopy[key] === 'object' && obj[key] !== null) {
Let's introduce function outside of deepClone function, in this case we could remove IIFE

2019-09-20 06:54 UTC, KalachevDev commented on tasks/77_expressions-matter/expressions-matter.js
> +  results.push(eval(`${a} + ${b} + ${c}`));
really? eval?

2019-09-20 06:54 UTC, KalachevDev commented on tasks/79_calculate_primoral_of_a_number/calculate_primoral_of_a_number.js
> + * //return 30
25?

2019-09-24 08:53 UTC, KalachevDev approved these changes

2019-09-25 07:36 UTC, vovcyan approved these changes

2019-09-25 07:37 UTC, merged